# Generated by Django 4.0.3 on 2022-03-24 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('release_date', models.DateField(null=True)),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('is_verified', models.BooleanField(default=False)),
                ('about', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tracks.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tracks.artist')),
            ],
        ),
    ]
